### ISSUE TITLE
Add support for URL query parameters

### ISSUE THREAD

**Issue by lnrdll** [GoogleCloudPlatform/jit-access#130]
Add support for URL query parameters in the application to facilitate easier linking and enhance user experience. This would allow users to share specific views within the app by simply appending query parameters to the URL.

This would be very helpful for documentation and playbooks where you can link to a specific project.

Example:

```
https://jit.example.com/home?project=<PROJECT_ID>
```

![image](https://github.com/GoogleCloudPlatform/jit-access/assets/25017746/41de1ea8-32d2-42f4-ba42-378dbe1d7fb5)

**Comment by jpassing** [comment]
That's a great idea, thanks.

**Comment by jpassing** [comment]
[Version 1.4.1](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.4.1) now includes this feature.
