### ISSUE TITLE
Permissions Issue After Deployment

### ISSUE THREAD

**Issue by mgrofsky** [GoogleCloudPlatform/jit-access#144]
**Issue**
When following the instructions at https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project

Deployment succeeds, but when selecting a project, including the project the JIT App Engine in, clicking "continue" returns a message "The project doesn't exist, or you don't have permission to activate any roles in this project"

The service account have `Cloud Asset Viewer` and `Security Admin` roles.

**Steps to reproduce**
Follow the steps on https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project
and place the App Engine JIT deployment in its own project.  

Add the add-iam-policy-binding scope to folder and use the folder ID to set the roles.

Assign your user the `IAP-secured Web App User` role and login and proceed to select a project in the folder within scope and continue.

**What would be expected?**
Clicking continue should accept the project selected and move to role activation.

**Comment by jpassing** [comment]
The message _The project doesn't exist, or you don't have permission to activate any roles in this project_ indicates that __you__ (the user who's authenticated to IAP, not the service account) hasn't been granted eligible access to this project yet. 

Once an admin [grants your user a role and adds the `has({}.jitAccessConstraint)` condition](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#grant_eligible_access), the error should disappear and instead, you should be offered to activate that role.

I hope this helps.

**Comment by mgrofsky** [comment]
Got it thank you.  It was a bit confusing that the role the conditiion has({}.jitAccessConstraint is assigned to, is the role that would be presented to the user.  This does make sense now.
