### ISSUE TITLE
Allow selecting multiple roles with multi-party-approval

### ISSUE THREAD

**Issue by kbelosevic** [GoogleCloudPlatform/jit-access#149]
If MPA is configured, we are only allowed to select only one role at a time.

We have a situation for infrastructure engineers (i.e. terraform) that will require a lot of roles at a time, so clicking daily on multiple roles is cumbersome.

Even when creating Custom IAM roles, we still have limit on number of permissions and etc so we end up having multiple custom roles.

**Comment by jpassing** [comment]
With [JIT Groups](https://googlecloudplatform.github.io/jit-access/jitgroups-concepts/), you can now bundle any number of roles (across multiple projects, if necessary) and let users request them at once. That should work well for the Terraform use case that you describe.

Note that JIT Groups supersedes the [JIT Access](https://googlecloudplatform.github.io/jit-access/jitaccess-overview/) project, which has largely outlived its purpose as privileged access management [is now available as a platform feature in Google Cloud ](https://cloud.google.com/iam/docs/pam-overview). JIT Groups addresses an adjacent, but different use case -- self-service access management, or entitlement management, for all types of Google Cloud access, not only privileged access.
