### ISSUE TITLE
Error during deploy

### ISSUE THREAD

**Issue by damiansztankowski** [GoogleCloudPlatform/jit-access#162]
Hello,

I've tried to use latest version of JIT, however, during deploy, I'm getting those errors:

`File upload done.
│ Updating service [default]...
│ .........................................................................................................................................failed.
│ ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build baf7b53d-2bed-4b16-9e91-e4d8dd4a1c38 status: FAILURE
│ ...from central: https://repo.maven.apache.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.2/plexus-compiler-manager-2.2.jar (4.6 kB at
│ 8.5 kB/s)
│ [INFO] Downloading from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.2/plexus-compiler-javac-2.2.jar (19 kB at 35
│ kB/s)
│ [INFO] Downloading from central: https://repo.maven.apache.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-classworlds/2.2.2/plexus-classworlds-2.2.2.jar (46 kB at 81 kB/s)
│ [INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-container-default/1.5.5/plexus-container-default-1.5.5.jar (217 kB
│ at 371 kB/s)
│ [INFO] Downloading from central: https://repo.maven.apache.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar (45 kB at 68 kB/s)
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar (134 kB at 205 kB/s)
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar (358 kB at 524 kB/s)
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar (121 kB at 168 kB/s)
│ [INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/collections/google-collections/1.0/google-collections-1.0.jar (640 kB at 874 kB/s)
│ [INFO] Changes detected - recompiling the module!
│ [INFO] Compiling 37 source files to /workspace/target/classes
│ [INFO] ------------------------------------------------------------------------
│ [INFO] BUILD FAILURE
│ [INFO] ------------------------------------------------------------------------
│ [INFO] Total time:  01:08 min
│ [INFO] Finished at: 2023-09-25T06:54:42Z
│ [INFO] ------------------------------------------------------------------------
│ [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jitaccess: Fatal error compiling: error:
│ invalid target release: 17 -> [Help 1]
│ [ERROR] 
│ [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
│ [ERROR] Re-run Maven using the -X switch to enable full debug logging.
│ [ERROR] 
│ [ERROR] For more information about the errors and possible solutions, please read the following articles:
│ [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
│ Full build logs: https://console.cloud.google.com/cloud-build/builds;region=europe-central2/baf7b53d-2bed-4b16-9e91-e4d8dd4a1c38?project=357490486308`

JIT version 1.4.1, downloaded from : https://github.com/GoogleCloudPlatform/jit-access/releases

cheers,
Damian

**Comment by jpassing** [comment]
Are you upgrading from a previous version of JIT Access? In that case, you need to make a change in your `app.yaml` to switch from Java 11 to Java 17:

```
sed -i 's/java11/java17/g' app.yaml
gcloud app deploy --appyaml app.yaml
```

For additional details, have a look at [Upgrade Just-in-Time Access](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#upgrade_just-in-time_access).

**Comment by damiansztankowski** [comment]
I did fresh install, from zero. Indeed I had old java line. Changed it. I've got this error
"
100%
│ File upload done.
│ Updating service [default]...
│ ......................................................failed.
│ ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 6f1fb4a1-4e43-49f9-b2f2-b8319c5c5c8d status: FAILURE
│ did not find any jar files with a Main-Class manifest entry
│ Full build logs:
│ https://console.cloud.google.com/cloud-build/builds;region=europe-central2/6f1fb4a1-4e43-49f9-b2f2-b8319c5c5c8d?project=788468064977"

Logs from Cloud Build:

"Starting Step #2 - "build"
Step #2 - "build": Already have image (with digest): eu.gcr.io/gae-runtimes/buildpacks/google-gae-22/java/builder:java_20230925_RC00
Step #2 - "build": ===> ANALYZING
Step #2 - "build": Timer: Analyzer started at 2023-09-26T04:47:37Z
Step #2 - "build": Image with name "eu.gcr.io/nc-ps-jit-45427/app-engine-tmp/app/default/ttl-18h:latest" not found
Step #2 - "build": Timer: Analyzer ran for 2.744491115s and ended at 2023-09-26T04:47:40Z
Step #2 - "build": ===> DETECTING
Step #2 - "build": Timer: Detector started at 2023-09-26T04:47:40Z
Step #2 - "build": 3 of 5 buildpacks participating
Step #2 - "build": google.java.runtime      0.9.1
Step #2 - "build": google.java.appengine    0.9.0
Step #2 - "build": google.utils.label-image 0.0.2
Step #2 - "build": Timer: Detector ran for 104.644641ms and ended at 2023-09-26T04:47:40Z
Step #2 - "build": ===> RESTORING
Step #2 - "build": Timer: Restorer started at 2023-09-26T04:47:40Z
Step #2 - "build": Layer cache not found
Step #2 - "build": Ignoring cache image "eu.gcr.io/nc-ps-jit-45427/app-engine-tmp/build-cache/default/ttl-7d:latest" because it was corrupt
Step #2 - "build": Timer: Restorer ran for 1.642908755s and ended at 2023-09-26T04:47:41Z
Step #2 - "build": ===> BUILDING
Step #2 - "build": Timer: Builder started at 2023-09-26T04:47:41Z
Step #2 - "build": === Java - Runtime (google.java.runtime@0.9.1) ===
Step #2 - "build": Using requested runtime feature version: 17.0
Step #2 - "build": 2023/09/26 04:47:41 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/openjdk/version.json
Step #2 - "build": ***** CACHE MISS: "openjdk"
Step #2 - "build": Installing  v17.0.8+7.
Step #2 - "build": 2023/09/26 04:47:41 [DEBUG] GET https://dl.google.com/runtimes/ubuntu2204/openjdk/openjdk-17.0.8_7.tar.gz
Step #2 - "build": Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #2 - "build": Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #2 - "build": Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #2 - "build": === Java - Appengine (google.java.appengine@0.9.0) ===
Step #2 - "build": Using GOOGLE_RUNTIME: java17
Step #2 - "build": --------------------------------------------------------------------------------
Step #2 - "build": Running "mv -f /builder/outputs/output-7503023080806884047 /builder/outputs/output"
Step #2 - "build": Done "mv -f /builder/outputs/output-7503023080806884047 /builder/o..." (25.620839ms)
Step #2 - "build": --------------------------------------------------------------------------------
Step #2 - "build": failed to build: building config: getting entrypoint: finding executable jar: (error ID: 838926df):
Step #2 - "build": did not find any jar files with a Main-Class manifest entry
Step #2 - "build": Timer: Builder ran for 6.201620542s and ended at 2023-09-26T04:47:47Z
Step #2 - "build": ERROR: failed to build: exit status 1
Finished Step #2 - "build"
ERROR
ERROR: build step 2 "eu.gcr.io/gae-runtimes/buildpacks/google-gae-22/java/builder:java_20230925_RC00" failed: step exited with non-zero status: 51
"

**Comment by radwo** [comment]
> Okay I found where was a problem. Issue can be closed. My automation performed action in wrong place.

I had the same issue, for 30 minutes couldn't get what was wrong.
I applied all the actions in the root folder of the repository, instead of `sources`. 🤦 

I hope this comment will help someone avoid same mistake in the future.
