### ISSUE TITLE
Offer pre-built images

### ISSUE THREAD

**Issue by lnrdll** [GoogleCloudPlatform/jit-access#174]
I'm curious if it's feasible to offer pre-built images for download from a publicly accessible repository. This would help expedite the deployment of the tool, eliminating the need for manual setup.

**Comment by jpassing** [comment]
I agree that a pre-built image would make the deployment a bit easier. But it's difficult to keep container images up-to-date and fully patched at all times, which is why we generally don't provide pre-built images for open-source projects. So the lack of pre-built images is currently intentional.
