### ISSUE TITLE
Development environment not exposing port 8080

### ISSUE THREAD

**Issue by danjamesmay** [GoogleCloudPlatform/jit-access#189]
Hi,

I'm following the [set up a development environment](https://github.com/GoogleCloudPlatform/jit-access/wiki/Development) instructions. I've installed JDK 17 and maven. I'm running the following commands but unable to reach the app entrypoint on `http://localhost:8080/?debug=1`.

I'm running the command as described in the wiki:

```sh
mvn -X quarkus:dev -s settings.xml -Ddebug=true -Djitaccess.debug=true -Dsuspend=y -Djitaccess.impersonateServiceAccount=jit-access-test@myproject.iam.gserviceaccount.com
```

I'm using custom settings to point to a proxy maven mirror.

I can only see port 5005 exposed and nothing listening on 8080.

```sh
➜  ~ ss -tlpn
State       Recv-Q      Send-Q           Local Address:Port           Peer Address:Port      Process
LISTEN      0           1                    127.0.0.1:5005                0.0.0.0:*          users:(("java",pid=80790,fd=113))
LISTEN      0           128                    0.0.0.0:22                  0.0.0.0:*
LISTEN      0           128                       [::]:22                     [::]:*
```

Nothing is being logged when hitting the endpoint. I've got stacktrace mode on for the `mvn` command.

```sh
[DEBUG] Launching JVM with command line: /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Dquarkus-internal.serialized-app-model.path=/home/aaa/dev/jit-access/sources/target/quarkus/bootstrap/dev-app-model.dat -javaagent:/home/aaa/.m2/repository/io/quarkus/quarkus-class-change-agent/3.2.3.Final/quarkus-class-change-agent-3.2.3.Final.jar -XX:TieredStopAtLevel=1 -agentlib:jdwp=transport=dt_socket,address=localhost:5005,server=y,suspend=y -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/aaa/dev/jit-access/sources/target/jitaccess-dev.jar
Listening for transport dt_socket at address: 5005
```

I haven't tried this in a debugger like intellij as I'm not a java developer. I'm trying to spin this up locally to test against.

**Comment by bschaatsbergen** [comment]
Are you overwriting the `PORT` environment variable by any chance? 
https://github.com/GoogleCloudPlatform/jit-access/blob/35f5be248ad0528a6115ceafcdb0d522ff0751c1/sources/src/main/resources/application.properties#L17

**Comment by jpassing** [comment]
The `-Ddebug=true -Dsuspend=true` flags cause the JVM to pause startup until you connect a debugger -- before even trying to start Quarkus. If you're not planning to use a debugger, remove the 2 flags from the command line.

**Comment by jpassing** [comment]
I assume this is resolved? Otherwise, please reopen this issue.
