### ISSUE TITLE
Question: Will this project be functional after the upcoming paywall for policy analyzer?

### ISSUE THREAD

**Issue by max-frank** [GoogleCloudPlatform/jit-access#193]
It seems that starting 2024 January some features of policy analyzer will be moved behind the paywall of Security Command Center. 
- https://cloud.google.com/policy-intelligence/docs/analyze-iam-policies
- https://cloud.google.com/policy-intelligence/docs/billing-questions#pricing-changes

To my understanding this project uses `AnalyzeIamPolicy` to retrieve the pre defined assignable roles. Currently this comes with somewhat reasonable quotas for organizations 
- 100 per minute per consumer project
- 1,000 per day per consumer project

In the pricing change announcement it is written:
> Policy Analyzer at scale (above 20 queries per day). This limit includes both allow policy analysis and organization policy analysis.

Which to my understanding would mean that jit-access could only retrieve the necessary IAM info 20 times a day (excluding any other tools using this API). Thus making it practically defunct for anyone without an org level Security Command Center subscription.

I am raising the question here to make sure my understanding of the inner workings of this project and the impact are correct (i.e., I might be confusing the utilized APIs here).

**Comment by jpassing** [comment]
Your understanding is correct: JIT Access uses the `AnalyzeIamPolicy` API to determine eligible roles and if you use JIT Access to activate a role, the application makes at least 2 such calls behind the scenes. 

Unfortunately, that means it's going to be difficult to use JIT Access without a Security Command Center subscription.

**Comment by max-frank** [comment]
Well thats unfortunate. Thanks for confirming. 
Feel free to close the question issue or leave it open for visibility 🙇

**Comment by bschaatsbergen** [comment]
It's unclear to me whether you can stil use JIT Access and Policy Analyzer at scale if you're on the Free (standard) version of Security Command Center on organisation level, or if you have to be on the Premium version? Do you know more about this @jpassing ?

**Comment by jpassing** [comment]
"At scale" use will [require  _organization-level activations of Security Command Center_](https://cloud.google.com/policy-intelligence/docs/billing-questions#pricing-changes:~:text=After%20January%2015%2C%202024%2C%20the%20following%20Policy%20Intelligence%20features%20will%20only%20be%20available%20for%20customers%20with%20organization%2Dlevel%20activations%20of%20Security%20Command%20Center%3A). In other words, you'll need Premium.

If you'd like to share feedback regarding this pricing change, I'd encourage you to reach out to your sales contact, they can pass your feedback to the responsible product teams.

**Comment by rostomzed** [comment]
@jpassing - Are there any changes required post Jan 2024 aside from having org-level SCC enabled?
Thanks.

**Comment by jpassing** [comment]
> @jpassing - Are there any changes required post Jan 2024 aside from having org-level SCC enabled? Thanks.

Not that I'm aware of -- I don't expect any code or config changes.

**Comment by jpassing** [comment]
#239 adds an alternate catalog implementation that uses `effectiveIamPolicies.batchGet` instead of `analyzeIamPolicy` to analyze role bindings. If you don't have an SCC subscription, you'll have the option to switch to this implementation. 

I'm planning to publish a release and update the documentation by end of next week,

**Comment by bschaatsbergen** [comment]
Amazing work @jpassing !

**Comment by jpassing** [comment]
If you'd like to give it a try: #239 is now merged to `master` and [this Wiki page](https://github.com/GoogleCloudPlatform/jit-access/wiki/Switch-to-a-different-catalog) describes how to switch to the `AssetInventory` catalog. 

If you experience any issues, please let me know.

**Comment by jpassing** [comment]
[Version 1.6](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.6.0) is out and if you're not an SCC subscriber, I you can now [upgrade to `latest`](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#upgrade_just-in-time_access) and then [switch to the `AssetInventory` catalog](https://googlecloudplatform.github.io/jit-access/configure-catalogs/#assetinventory-catalog). If you experience any issues with that, please report them as new issues.
