### ISSUE TITLE
UI enhancement request: Role sorting

### ISSUE THREAD

**Issue by ToyB0x** [GoogleCloudPlatform/jit-access#220]
Hi, Thank you for creating such a useful tool.

As a small request on the UI,
I thought it would be easier to use if the roles were sorted and displayed.

(For reference, I have attached a screenshot of how the strings are not sorted in v1.5.0)
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/83337042/ea3ae052-1f19-43a8-b0b3-8cedef6473d3)

**Comment by jpassing** [comment]
This has just been implemented as part of #213. It's not part of release 1.5, but it's already available in the `master` branch.
