### ISSUE TITLE
Reauthenticate the Google account

### ISSUE THREAD

**Issue by elamcheliyan** [GoogleCloudPlatform/jit-access#246]
When the user gets the just-in-time approval, we would like to force the re-authentication of Google single-sign-on. Just for security reasons. Is it possible to do so in the application?
If not suggest is there any other way?

**Comment by jpassing** [comment]
Yes, you can do that by configuring [IAP reauthentication](https://cloud.google.com/iap/docs/configuring-reauth).

**Comment by elamcheliyan** [comment]
Thanks
