### ISSUE TITLE
Automation of JIT access application deployment in Cloud APP engine

### ISSUE THREAD

**Issue by elamcheliyan** [GoogleCloudPlatform/jit-access#259]
I would like to automate the below steps in Terraform
https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#organization

Especially, the Cloup APP engine deployment, Shall we try this terraform resource? or do you have any other suggestion?
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/app_engine_standard_app_version

**Comment by damiansztankowski** [comment]
Hi,

I've terraformized this deployment and used AppEngine. Combination of gcloud scripts, terraform and I'm able to provision this from code.

This is how my main.tf looks:

`module "jit-deploy" {
  source                     = "./modules/terraform-just-in-time"
  outh_support_email         = "" # example: "members@example.com"
  billing_account            = "" # example: "BILLING_ACC_ID"
  org-id                     = "" # example: "256007354632"
  sa-credentials             = "modules/terraform-just-in-time/credentials/credentials.json"
  support_group = ""    # example: "google-cloud-premium-support@example.com"
  access_at_folder_level     = false # possible options "true/false"
  access_at_org_level        = true  # possible options "true/false"
}

output "jit-deploy" {
  value = module.jit-deploy.AppInfo
}`

 "sa-credentials" -> static json is faster, however you should have key rotation for SA. You can use WIF and WIF pools + GH Actions to trigger deployment or you can run deployment directly from gcloud shell.
 
 
 cheers,
 Damian

**Comment by elamcheliyan** [comment]
Does anyone have an idea? What is to be provided in the below block? because in the app.yaml file. There is no entrypoint field defined
entrypoint {
**shell = "node ./app.js"**
}

**Comment by jpassing** [comment]
[Here's an example](https://github.com/GoogleCloudPlatform/jit-access-bastion-host-tf/blob/aad4c9aa3d5fd869da36b1793fff6c4434119bd0/jit-app/main.tf#L112) that might help. It's a bit outdated though and you'll have to change

```
runtime         = "java11"
```

to

```
runtime         = "java17"
```

**Comment by elamcheliyan** [comment]
This solution works
entrypoint {
shell = ""
}
Thanks
I will close this requesyt

**Comment by elamcheliyan** [comment]
I will close this request
