### ISSUE TITLE
SMTPSendFailedException

### ISSUE THREAD

**Issue by elamcheliyan** [GoogleCloudPlatform/jit-access#269]
runtime: java17
env: standard
instance_class: F2

**We are getting a SMTPSendFailedException error 530-5.7.0 authentication required.**
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/65539745/cd1f5588-39bb-48f8-b434-f536a8c28c38)

We have followed below Google Workspace email configuration in app.yaml file
 SMTP_ENABLE_STARTTLS: 'True'
 SMTP_PORT: '587'
 SMTP_SECRET: projects/xxxxxxxxxx/secrets/jitaccess-smtp/versions/2
 SMTP_SENDER_ADDRESS: jitaccess-notifications@xxxxx.com
 SMTP_SENDER_NAME: jitaccess

https://googlecloudplatform.github.io/jit-access/configure-multi-party-approval/

Do you have any idea what the problem could be? Is it "app password" problem?

**Comment by elamcheliyan** [comment]
Recent obervation:

2024-02-06 16:37:59.968
The mail could not be delivered caused by AuthenticationFailedException: 534-5.7.9 Please log in with your web browser and then try again. For more
534-5.7.9 information, go to

![image](https://github.com/GoogleCloudPlatform/jit-access/assets/65539745/56adc2aa-b88b-4f68-bae4-5f436435f26f)

On the App passwords page, use the following settings:
    Select app: Select Mail
    Select device: Select Other and enter a name such as JIT Access

There is no option for me to select app and the device for setting app password in the above picture

**Comment by jpassing** [comment]
The error might be related to licensing: Could you verify that the user `jitaccess-notifications@` has a Workspace license assigned and can access https://mail.google.com/?

**Comment by elamcheliyan** [comment]
We have a license with Google Workspace. I don't know the root cause of this problem.
We configured it with a Microsoft 365 email account to solve the problem, and now the email is working.

**Comment by jpassing** [comment]
Thank you for confirming that this works now.

I guess there isn't anything to follow up on on the JIT Access side, so I'll close this issue.
