### ISSUE TITLE
Unable to deploy 1.6.0

### ISSUE THREAD

**Issue by pranav-joshi-harness** [GoogleCloudPlatform/jit-access#270]
severity: "ERROR"
textPayload: "terminated: Application failed to start: failed to load /usr/bin/java: exec format error"
timestamp: "2024-02-08T10:48:28.268077304Z"

**Comment by jpassing** [comment]
`/usr/bin/java: exec format error` typically indicates a CPU architecture mismatch. Is it possible that you're building the Docker image on an arm64 machine? That might explain the mismatch as Cloud Run expects x64.

The documentation and deployment instructions currently assume that you're running on x64... which is something to be fixed. In the meantime, a workaround would be to execute the deployment steps in Cloud Shell (which is x64).

**Comment by pranav-joshi-harness** [comment]
Thanks.
