### ISSUE TITLE
Publish official docker image

### ISSUE THREAD

**Issue by florianmutter** [GoogleCloudPlatform/jit-access#287]
Is there any reason this is not publish as a docker image to gcr.io public registry? Seems wierd that we need to build it on our own. Also makes it harder to automate updates with a bot.

**Comment by jpassing** [comment]
I agree that a pre-built image would make the deployment a bit easier. But it's not trivial to keep container images up-to-date and fully patched at all times -- as a matter of policy, we therefore don't provide pre-built images for open-source projects like this one. So the lack of pre-built images is currently intentional and I'm afraid not something we can change.

**Comment by florianmutter** [comment]
Understood. Thank you for the feedback

**Comment by aebrahim** [comment]
@jpassing - Can this decision be re-visited?

It is quite shocking to hear an admission from someone at GCP that it is difficult to keep an image patched and up to date - given that y'all have access to both Google's internal tooling AND Google Cloud Platform itself. This is the same issue that customers like us face, and GCP advertises solutions to this exactly problem. In fact, we are considering expanding our use of GCP to use Cloud Build coupled with  [Artifact analysis and vulnerability scanning](https://cloud.google.com/artifact-registry/docs/analysis) to keep our own deployed containers patched and up to date.

If GCP thinks these tools are not effective to maintain images for itself, surely customers like us shouldn't use them either, and that is a pressing issue which needs to be addressed?

Thank you for hearing me out.

**Comment by jpassing** [comment]
@aebrahim, I hear you and I don't disagree. Publishing a BinAuthz-attested image would probably be ideal. 

However, the decision to not publish images isn't specific to this project -- it's a general policy for Google Cloud open-source projects and I currently don't see how we could deviate from that.

**Comment by florianmutter** [comment]
FYI: Here is the terraform code we use to build the image. Not perfect because it rebuilds the image every run but good enough for us:
```hcl
locals {
  temp_folder        = "${path.module}/.terraform/.tmp/jitaccess-files"
  jit_access_version = "1.6.0"
  registry           = "${var.region}-docker.pkg.dev"
  image_name         = "${local.registry}/${var.target_project_id}/${google_artifact_registry_repository.jitaccess.name}/jitaccess:${local.jit_access_version}"
}

data "http" "jitaccess_release_content" {
  url = "https://github.com/GoogleCloudPlatform/jit-access/archive/refs/tags/${local.jit_access_version}.tar.gz"
}

resource "local_sensitive_file" "jitaccess_release" {
  filename       = "${local.temp_folder}/jitaccess.tar.gz"
  content_base64 = data.http.jitaccess_release_content.response_body_base64
}

resource "null_resource" "extract_jitaccess" {
  provisioner "local-exec" {
    command = "tar xzf ${local_sensitive_file.jitaccess_release.filename} --strip-components 1 --directory ${local.temp_folder}"
  }
  triggers = {
    content_sha256 = local_sensitive_file.jitaccess_release.content_sha256
    filename       = local_sensitive_file.jitaccess_release.filename
  }
  depends_on = [local_sensitive_file.jitaccess_release]
}

resource "docker_image" "jitaccess" {
  name = local.image_name
  build {
    context = "${local.temp_folder}/sources"
  }

  depends_on = [null_resource.extract_jitaccess]
}

resource "docker_registry_image" "jitaccess" {
  name          = docker_image.jitaccess.name
  keep_remotely = true
}
```
