### ISSUE TITLE
Document health check

### ISSUE THREAD

**Issue by aebrahim** [GoogleCloudPlatform/jit-access#320]
We are working on deploying this in cloud run. Are there startup and health check endpoints we can give cloud run (e.g. `/health`) for the cloud run startup and liveness probes?

Thank you!

**Comment by jpassing** [comment]
So far, there hasn't really been a need for a dedicated health check endpoint: the app is stateless and starts up pretty quickly. But if you think it would be good to have a dedicated endpoint, I'd be happy to add one.

**Comment by jpassing** [comment]
[Version 1.7](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.7.0) now implements [liveness- and readiness endpoints](https://googlecloudplatform.github.io/jit-access/health-checks/). For now, the checks are pretty light, but we could add additional/more thorough checks to the readiness endpoints.

I'll close this issue now, but feel free to re-open it or to file a new issue if there's anything missing or not working as expected.
