### ISSUE TITLE
How to send Emails via Gmail without allowing less secure apps?

### ISSUE THREAD

**Issue by florianmutter** [GoogleCloudPlatform/jit-access#339]
According to https://support.google.com/accounts/answer/6010255?hl=en less secure apps will not be allowed some time later this year.
It seems to me that SMTP with app password does only work if less secure apps are allowed.

Is there any alternative to app passwords that we can use?

EDIT: Maybe jit-access needs to use the [gmail api](https://developers.google.com/gmail/api/guides) to send emails?

**Comment by jpassing** [comment]
_Less secure apps_ and _app passwords_ are unrelated: You can disable _less secure apps_ and it should have no impact on _app passwords_. The upcoming deprecation of _less secure apps_ therefore shouldn't affect JIT Access.

> Maybe jit-access needs to use the [gmail api](https://developers.google.com/gmail/api/guides) to send emails?

That would certainly work, but not everybody uses Gmail for email delivery. So we'd have to maintain 2 mechanisms for email delivery, and I'm not sure if that's worth it.

**Comment by florianmutter** [comment]
We did create a new workspace account, enabled 2-FA and created a app password.

Setting "Allow users to manage their access to less secure apps" in Google Admin console allows us to send emails. This is the only thing we changed. Setting this to "Disable access to less secure apps (Recommended)" prevents us from sending emails. Documentation of this setting here: https://support.google.com/a/answer/6260879?hl=en

We did not change any setting for the user itself.

The error we get is:
> User florian.mutter@example.com failed to request role 'roles/artifactregistry.writer' on '//cloudresourcemanager.googleapis.com/projects/puc-d-ce-jit-access-faf3' for 5 minutes: The notification could not be sent, caused by MailException: The mail could not be delivered, caused by AuthenticationFailedException: 534-5.7.9 Please log in with your web browser and then try again. For more
534-5.7.9 information, go to
534 5.7.9  https://support.google.com/mail/?p=WebLoginRequired g18-20020a170906199200b00a46b0d47710sm5321781ejd.161 - gsmtp

Any idea what we could do?

**Comment by florianmutter** [comment]
I created a app password for my user and it works. It seems to be an issue with the jit-access user we created for this.

**Comment by jpassing** [comment]
I also did some internal reasearch yesterday but couldn't find anything that would explain why disabling LSAs would have an impact on application-specific passwords. In fact, one of my test accounts uses the same configuration: LSA disabled, but JIT Access uses an ASP to send emails.

> I created a app password for my user and it works. It seems to be an issue with the jit-access user we created for this.

In that case, maybe just delete and recreate the jit-access user?  And if you haven't already, make sure it has a Workspace license. The error message doesn't indicate a license issue, but a Workspace license is required to send emails.
