### ISSUE TITLE
Configure multi party approval found error

### ISSUE THREAD

**Issue by Donrawat** [GoogleCloudPlatform/jit-access#365]
Hello

I've already set up the multi approval and attempt request roles, however I found the error shown in pictures [1][2][3] and the error shown in the log on GCP's Log Explorer as below.

"User xxx@yyy.net failed to request role 'roles/compute.admin' on '//cloudresourcemanager.googleapis.com/projects/xxx-yyy-zzz' for 5 minutes: The notification could not be sent, caused by MailException: The mail could not be delivered, caused by AuthenticationFailedException: 534-5.7.9 Please log in with your web browser and then try again. For more
534-5.7.9 information, go to
534 5.7.9  https://support.google.com/mail/?p=WebLoginRequired k63-20020a638442000000b005fd88b393b4sm5524465pgd.59 - gsmtp"

Why does the problem occurring even though I have 2-MFA setup and am using the app password on Google Admin for application as document [1]?

[1] https://googlecloudplatform.github.io/jit-access/configure-multi-party-approval/

![1  multi_approval](https://github.com/GoogleCloudPlatform/jit-access/assets/117263256/699fd218-e25f-46d7-bef5-bbebf2017491)
![2  multi_approval](https://github.com/GoogleCloudPlatform/jit-access/assets/117263256/2ad6122b-0f1c-4ef7-b866-3aad9008f86d)
![3  multi_approval_error](https://github.com/GoogleCloudPlatform/jit-access/assets/117263256/0f6d3060-16a2-491b-b569-81dec942433e)

Thank you ,
Donrawat Nawipun

**Comment by jpassing** [comment]
The user account that you specified in `SMTP_SENDER_ADDRESS` requires a Workspace license to be allowed to send email. Could you verify that you assigned a license? Otherwise that might explain the error message.

**Comment by Donrawat** [comment]
After I have changed the user account that specified in SMTP_SENDER_ADDRESS, It can select approval as shown in picture [4], but the mail box for user account shown error in picture [5]


[4]
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/117263256/91eb4098-dfb5-4d82-9cde-97093ae91f93)
[5]
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/117263256/c674bdbc-8d26-4cc9-9ec3-9460dc30c5e5)

**Comment by jpassing** [comment]
By default, JIT Access assumes that Cloud Identity/Workspace user names are valid email addresses. So if you pick `bob@example.com` as approver, it'll send an email to `bob@example.com` .

Is it possible that you picked an approver whose username _is not_ a valid email address? That would explain the delivery-failed error.

If user names systemtatically differ from email addresses in your environment, you can use [`SMTP_ADDRESS_MAPPING`](https://googlecloudplatform.github.io/jit-access/configuration-options/#notifications:~:text=SMTP_ADDRESS_MAPPING) to define a mapping between the two. But if this issue only applies to that particular user you tested with, then maybe just try a different user.

**Comment by jpassing** [comment]
Closing this issue as I haven't heard back. Please reopen if the problem still applies.
