### ISSUE TITLE
Cloud APP engine still using TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by elamcheliyan** [GoogleCloudPlatform/jit-access#366]
Hi,
We deployed the JIT application in Google cloud app engine with the default appspot.com domain.
During our pent test, we found that they are still using TLS1.0 and 1.1 
How to get rid of these version and use instead  TLS 1.2

Any idea? or Do we need to contact Google for this?

**Comment by jpassing** [comment]
I don't think it's possible to restrict TLS versions for the default `.appspot.com` endpoint. However, you can deploy a [load balancer with a serverless NEG](https://cloud.google.com/blog/products/networking/better-load-balancing-for-app-engine-cloud-run-and-functions) in front of the AppEngine app, and then you can use [SSL policies](https://cloud.google.com/load-balancing/docs/ssl-policies-concepts) to adjust settings.

**Comment by jpassing** [comment]
Yes, you'll need a custom domain. But it could be a subdomain of a domain that you already own.

**Comment by elamcheliyan** [comment]
We have registered a new custom domain from Google. With respect to the deployment any change is needed especially in app.yaml file configuration as we are now introducing LB in front of app engine.

cat << EOF > app.yaml

runtime: java17
instance_class: F2
service_account: $SERVICE_ACCOUNT
env_variables:
    RESOURCE_SCOPE: $SCOPE_TYPE/$SCOPE_ID
    RESOURCE_CATALOG: AssetInventory
    RESOURCE_CUSTOMER_ID: $ACCOUNT_CUSTOMER_ID
    ACTIVATION_TIMEOUT: 60
    JUSTIFICATION_HINT: "Bug or case number"
    JUSTIFICATION_PATTERN: ".*"
EOF

**Comment by jpassing** [comment]
If you use a [serverless NEG](https://cloud.google.com/load-balancing/docs/negs/serverless-neg-concepts) to deploy a load balancer in front of AppEngine, then I don't think you'll need to change the JIT Access configuration at all. However, the resulting setup will deviate from the [two "standard" deployment patterns documented here](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project) and I've never tested this kind of setup myself.

Another option would be to switch from AppEngine to Cloud Run. You could use your existing project and service account, [follow the steps to deploy JIT Access on Cloud Run](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#cloud-run) in the same project (which includes setting up a load balancer) and once that works, undeploy the AppEngine app.

**Comment by jpassing** [comment]
I'll go ahead and close this issue. If you encounter further issues or questions, please feel free to reopen it.
