### ISSUE TITLE
Error: MDCSliderFoundation: value must be in [min, max] range. Current values: [value: 50, min: 5, max: 30]

### ISSUE THREAD

**Issue by ottlngr** [GoogleCloudPlatform/jit-access#378]
Hi,

I just deployed jitaccess:1.7.0 on Cloud Run.
After selecting a role and clicking on "Request Access" the following error message appears:

![image](https://github.com/GoogleCloudPlatform/jit-access/assets/11619414/ce2a01ba-ffae-4c15-8a13-c6a3bd78469b)

**Comment by jpassing** [comment]
Thank you for reporting this issue.  This error occurs when [`ACTIVATION_TIMEOUT`](https://googlecloudplatform.github.io/jit-access/configuration-options/#:~:text=1.6-,ACTIVATION_TIMEOUT,-%2C%0A%0ADeprecated%3A) is set to `50` or below (you seem to be using `30`). I'll fix this shortly. 

As a possible workaround, you could temporarily increase your `ACTIVATION_TIMEOUT` setting to `50`.

**Comment by ottlngr** [comment]
Thanks for the quick reply and the fix.

Setting `ACTIVATION_TIMEOUT` to 50 did not work for me, but I built the image from the `fix/timeout-slider` branch and this works.

**Comment by jpassing** [comment]
Great, thanks for confirming that the fix works. I'll close this issue then.
