### ISSUE TITLE
Feature request: Ability to specify project in the url query parameters

### ISSUE THREAD

**Issue by rwblokzijl** [GoogleCloudPlatform/jit-access#414]
In our usecase people usually come to the JIT app through some link we automatically give them as part of an error message when they don't have enough permissions to run a command. It would be nice if we could specify the project directly for the use in this URL:

```
https://jit-app.example.com/?project=project-abc123
```

This way the user does not have to know the project id, which usually is quite an ugly string including a random_id anyway, since it has to be globally unique. Note that GCP allows the `?project=` parameter as well to specify a project.

**Comment by jpassing** [comment]
This feature is available already: If you're using version 1.4.1 or newer, you can add a query string `?projectId=project-abc123` and then JIT Access automatically selects that project.
