### ISSUE TITLE
When the role is too long, it exceeds the box (UI/visual) in the e-mail

### ISSUE THREAD

**Issue by fancybear-dev** [GoogleCloudPlatform/jit-access#439]
Hi,

This is very minor, but given it was not reported before afaik and it likely is an easy fix; 

![image](https://github.com/user-attachments/assets/cdd7b42e-e2da-4477-aad6-dae2332070b3)

When a role string is too long, it exceeds the box. This visual was loaded in Outlook browser, on a widescreen 4k monitor.

We run this version; https://github.com/GoogleCloudPlatform/jit-access/tree/95c4257c963e37498b00e2ebe7cbd92409f4a702

**Comment by jpassing** [comment]
This seems to be somewhat specific to Outlook. In Gmail, it looks okay:

![image](https://github.com/user-attachments/assets/1ef60bff-dbd1-4954-8826-40ec4953ae34)

I changed the email template to break word more aggressively. In Gmail, it now it looks like this:

![image](https://github.com/user-attachments/assets/1df3eea8-0c87-4ae2-a831-dcd000fc08a5)

Unfortunately, I don't have access to a Desktop Outlook at the moment, so I'm not sure if Outlook honors this CSS style.

**Comment by fancybear-dev** [comment]
@jpassing thank you! Once we have the update in production, we'll test it out and come back to you on this.

Wanted to explicitly thank you in general for this application and project. We've been using it throughout our cloud environment within scoped and isolated environments and we wouldn't have been able to achieve our security goals without this.

**Comment by jpassing** [comment]
It looks okay now in Outlook (Web):

![image](https://github.com/user-attachments/assets/8d33d60e-3620-4d9e-9313-0e95e5f84ef7)

I also checked Desktop Outlook and while it's less pretty, the text is wrapped correctly there too.

The change is now available in [release 1.8.1](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.8.1), so I'll close this issue.
