### ISSUE TITLE
Add a time interval option in the JIT access request UI

### ISSUE THREAD

**Issue by dneduva-cisco** [GoogleCloudPlatform/jit-access#52]
As an enhancement, we would like the option to request the amount of time a user is given access to a certain role in JIT as part of the request. 
We would like that to be an option in the JIT UI instead of an environment variable in the app.yaml.

**Comment by jpassing** [comment]
I agree that this would be a useful feature. The `ACTIVATION_TIMEOUT` (in `app.yaml`) would then define an upper bound (for ex, 2h). Users could choose to activate a role for a shorter period of time (for ex, only 30min), but couldn't go beyond that upper bound.

**Comment by jpassing** [comment]
This feature is now available in [release 1.4](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.4.0): You can now choose the duration for which to activate a role, between 5 minutes and the maximum duration specified by [ACTIVATION_TIMEOUT](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration).

**Comment by lnrdll** [comment]
Could we log the duration for which the user has requested elevation?

**Comment by jpassing** [comment]
The logs contain the start and end date in the `activation_start` and `activation_end` labels:

![image](https://user-images.githubusercontent.com/5724941/233225887-91206ca1-9bcc-4fa4-b84c-8a203e297f54.png)

This (implicitly) gives you the duration. We could add an extra label for duration, but I guess it would be somewhat redundant?

**Comment by lnrdll** [comment]
I think I overlooked these entries. No need for an extra label. Thanks!
