### ISSUE TITLE
ability to require multiple approvals

### ISSUE THREAD

**Issue by rojomisin** [GoogleCloudPlatform/jit-access#55]
One feature that would be useful for the MPA worklfows is to set to have `MIN_APPROVERS=2`, where if there's 5 `ACTIVATION_REQUEST_MAX_REVIEWERS` in the list, 2 would be required, otherwise default to 1 approval only.

**Comment by rojomisin** [comment]
I assume the lack of state being the reason 2 is more difficult, yeah honestly the Slack feature might help w/ visibility and awareness of approvals amongst peers. The feedback originally was that some only check their email once a day.  

Implementation of 1 could be a slight boost as well, otherwise someone might just try and skirt around the more scrutinizing senior members, and opt to get approval from the intern :)

**Comment by jpassing** [comment]
This feature is now available in [release 1.4](https://github.com/GoogleCloudPlatform/jit-access/releases/tag/1.4.0), see [`ACTIVATION_REQUEST_MIN_REVIEWERS`, `ACTIVATION_REQUEST_MAX_REVIEWERS`](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration).

Thanks again for the feature suggestion!
