### ISSUE TITLE
Does Jit Access support service accounts?

### ISSUE THREAD

**Issue by arairyus** [GoogleCloudPlatform/jit-access#62]
Does JIT Access only support IAM users or groups?
I tried using `has({}.jitAccessConstraint)` for the service account role, but it does not show up in the JIT Access web UI.
I would like to use JIT to control `roles/iam.serviceAccountUser` for a specific IAM group for a specific service account.

**Comment by jpassing** [comment]
Yes, you can grant a user or group the `roles/iam.serviceAccountUser` role and add a `has({}.jitAccessConstraint)` condition to that role binding. Then the role will show up in the UI:

![image](https://user-images.githubusercontent.com/5724941/228089400-4ce3456c-51dc-445b-a526-063d2db81994.png)

However, the application only considers roles granted at the organization-level, folder-level, or project-level. It won't consider roles granted at the resource level. So you can grant a user JIT access to _all_ service accounts in a project, but it's not possible to grant JIT access to _one particular_ service account.

**Comment by arairyus** [comment]
> So you can grant a user JIT access to all service accounts in a project, but it's not possible to grant JIT access to one particular service account.

Thank you!
I now have a better understanding of the JIT application specifications.
