### ISSUE TITLE
Show peer approvers from the group only to which the requester belongs to

### ISSUE THREAD

**Issue by stigori** [GoogleCloudPlatform/jit-access#77]
Based on the [Multi Party Approval](https://github.com/GoogleCloudPlatform/jit-access/wiki/Multi-Party-Approval) documentation, "If **two users are granted an MPA-eligible role binding** for, say roles/compute.admin on project-1, then **they can approve each other’s requests**."

In short, the **qualified approvers** will be those who **the requester shares the MPA-eligible role binding**.

However, it has been observed, when the same condition is set for more than one group on a given scope, but with different description, only the first found group's members are listed as approvers.

### Steps to reproduce

1. Apply a multi-part approval IAM condition for a role on two different groups on the same level, using different description.
2. Elevate the user's permission using the configured JIT role.

Peer approvals will be visible from the first found group only.

### What would be expected?

Peers should be listed from the group only, that grants the eligibility to the user.

### How we think this could be achieved?

The description of the set condition should be taken into consideration when listing the potential approvers.

Our use-case is that we give JIT roles based on group membership and we define in the condition's description which group membership gives access to a certain role, however if a different group's members can elevate their privileges to the same role (using JIT), when listing for approvers only one of the group members will be shown - unless the two conditions are identical (including description).

Currently this configuration forces us n**ot to use unique descriptions in the condition**, that lists approvers from all the groups that has access to the same type of JIT role.

### Scenario to image

A Logging Admin role is granted both to group A and group B through the same JIT condition on the organization scope. A member in group A wants to elevate its privileges, that requires peer approval. When listing the approvers, peers will be visible both from group A and group B, whereas approvers should be listed from the group, that made the requester eligible to a certain role.

**Comment by jpassing** [comment]
Sorry for the delayed response.

> when the same condition is set for more than one group on a given scope, but with different description, only the first found group's members are listed as approvers.

This is interesting. The title and description of the IAM condition shouldn't have any impact -- but evidently they do, and I was able to reproduce the behavior you described. This doesn't seem to be a bug in JIT Access though. Instead, it's the underlying Cloud Asset API (`analyzeIamPolicy`) that seems to produce an incomplete result in this scenario. I internally filed a bug for that.

What I'd expect to happen in the scenario is to see approvers from both groups. It really shouldn't matter _how_ somebody has been granted an MPA-eligble role binding (via the same or a different group or directly): If they are MPA-eligble for the same project and role, they should show up as a approver.

Is that also what you'd expect?

**Comment by jpassing** [comment]
I don't have any news to share on the underlying the PolicyAnalyzer API. However, the (new) `AssetInventory` catalog should be unaffected by this problem, so I think the best path forward would be to [change the configuration of JIT Access to use that instead](https://googlecloudplatform.github.io/jit-access/configure-catalogs/).
