### ISSUE TITLE
Running the app in debug mode

### ISSUE THREAD

**Issue by stiyya** [GoogleCloudPlatform/jit-access#86]
I have a case where when I do a manual deploy the app works fine ,but when I deploy using terraform code , the app does not function as expected. I just get a blank page with Just-In-Time Access and it does not say signed in as myself, does not list any options for projects etc.The GCP logs show no errors or warnings. Trying to see if I can run this debug mode.  And how would I do that ? 
The same terraform code works fine in a different GCP project. 
<img width="1245" alt="Screenshot 2023-06-14 at 2 00 31 PM" src="https://github.com/GoogleCloudPlatform/jit-access/assets/136639811/4e34e927-d5e4-414d-96f4-9b0f2d057f13">

GCP has been of zero help. trying to see if I anyone has run into this issue before. Or if you can show me how to enable debug on this application to get more logs. 

Thank you

**Comment by jpassing** [comment]
Could you try the following?

1. Open an incognito browser window
2. Navigate to `https://<your-jitaccess-domain>/api/policy`

What should happen is:

1. IAP prompts you to sign in 
2. The server returns a `message: "Missing header: X-JITACCESS"`

Is that's what your're seeing too?

**Comment by stiyya** [comment]
Yes , that is what I see when deployed with terraform.

**Comment by jpassing** [comment]
Ok. IAP seems to be working correctly then, and something must be wrong with the JIT Access configuration.

Are you deploying to Cloud Run or AppEngine? If it's Cloud Run, then I'd suggest to double-check that [`IAP_BACKEND_SERVICE_ID` is set correctly](https://cloud.google.com/architecture/manage-just-in-time-privileged-access-to-project#:~:text=name%3A%20IAP_BACKEND_SERVICE_ID). If `IAP_BACKEND_SERVICE_ID` is empty or contains the wrong ID, then the `latest` version currently fails silently -- just as you describe. FWIW, this is [fixed in the `master`](https://github.com/GoogleCloudPlatform/jit-access/pull/80), branch.

**Comment by stiyya** [comment]
I am using App Engine. Is there anything I can do to run this in debug mode to get more logging ?

**Comment by jpassing** [comment]
There's a debug mode, but it's only intended for development, so I'm afraid it won't be useful in your case. I am a bit surprised that there are no logs at all -- you should at least see logs indicating successful IAP authentication. 

As a next step, it might be helpful to check the following:

1. Open a browser and nabigate to the JIT access app
2. Open the Chrome dev tools (F12) and activate the **Network** tab
3. Refresh the page
4. In the **Network** tab, find the request to `policy` and open the details
5. Open the **Response** tab

You should see a JSON respnse like this:
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/5724941/175228c6-d531-45d9-9bf7-bf52390183fc)

Do you see an error instead? If so, which one?

**Comment by stiyya** [comment]
Looks like the model.js file and the ones following that are throwing a 404 error. Does not make it to policy. 
<img width="1683" alt="Screenshot 2023-06-16 at 11 17 50 AM" src="https://github.com/GoogleCloudPlatform/jit-access/assets/136639811/366017b7-352b-49a6-a124-73c5fd0a75ca">

**Comment by jpassing** [comment]
`model.js` and `styles.css` are both static files and are stored in the same directory, yet one gives a 404 and the other one works. Is it possible that your `.gcloudignore` or something else blocks the deployment of `.js` files to AppEngine?
