### ISSUE TITLE
Optionally remove the restriction on maximum recipients for peer review activation requests email

### ISSUE THREAD

**Issue by TKBP** [GoogleCloudPlatform/jit-access#89]
Hi,

Today if a JIT controlled role has multi party approval enabled and there are more than 10+ in a team who can approve/review the requests, and the requester uses the "Select all" checkbox -  the UI shows an error that there can be maximum 10 recipients. This makes using the checkbox difficult because with our organization most of the groups/app teams are more than 10 people.

We're using an internal SMTP relay to deliver the emails and certainly have no intentions to spam the world with JIT requests, could this restriction be turned off if let's say the SMTP relay is not gmail.com/outlook.com etc?

Thank you!

**Comment by jpassing** [comment]
You can adjust the maxiumum number of reviewers by adding the environment variable [`ACTIVATION_REQUEST_MAX_REVIEWERS`](https://github.com/GoogleCloudPlatform/jit-access/wiki/Configuration#:~:text=ACTIVATION_REQUEST_MAX_REVIEWERS) to your `app.yaml` (requires version 1.4). Maybe you can use that and set the limit to `100` or so?

**Comment by TKBP** [comment]
I'm sorry, silly me. Thanks for this, I missed it. We will try shortly!

**Comment by jpassing** [comment]
No worries :) 

I'll close this issue then -- if something still doesn't work after adding the environment variable, you can just reopen it.
