### ISSUE TITLE
"At least one role is required (HTTP 400: error)"

### ISSUE THREAD

**Issue by damiansztankowski** [GoogleCloudPlatform/jit-access#90]
Hello,

I'm using JIT to enable self-approval process for projects placed at dedicated folder, so  JIT configuration is set to **folder**. Due to errors with custom roles, I'm granting few **Viewer roles like Compute Viewer, Logging Viewer** and so on. Unfortunately, when I want to choose all roles and request access, I'm getting error **"At least one role is required (HTTP 400: error)".** I've tried to use latest version of JIT as well as version from master branch, both giving mentioned error . What is interesting, I'm able to activate all roles one by one, but not in a bulk. 
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/71320767/a16647cf-f739-46bc-847e-28045ed74759)
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/71320767/57da2544-26fa-4717-9dfd-65c87f7c632a)

cheers,
Damian

**Comment by jpassing** [comment]
The app currently lets you activate at most 10 roles at once, and if you select more it returns the (rather unhelpful) error "At least one role is required". See [issue #83 for more details](https://github.com/GoogleCloudPlatform/jit-access/issues/83#issuecomment-1583893219).

**Comment by damiansztankowski** [comment]
Ahh, I see. Thanks
