### ISSUE TITLE
Unable to Integrate Billing Permissions in JIT

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [GoogleCloudPlatform/jit-access#98]
Hello

I have experienced an issue when attempting to incorporate either default (not primitive), or custom billing-based permissions into JIT.

Example custom role (deployed with `terrform`) is `infra.analyst.billing.write`. Example of errors from my workflows when attempting 

```
│ Error: Error applying IAM policy for organization "X": Error setting IAM policy for organization "X": googleapi: Error 400: Role roles/infra.analyst.billing.write is not supported for this resource., badRequest
│ 
│   with module.organization-iam-bindings.google_organization_iam_member.organization_iam_additive["default--roles/infra.analyst.billing.write--group:X@Y.com"],
│   on .terraform/modules/organization-iam-bindings/modules/organizations_iam/main.tf line 49, in resource "google_organization_iam_member" "organization_iam_additive":
│   49: resource "google_organization_iam_member" "organization_iam_additive" {
```

I confirmed that the role has been procured and is valid at org-level within GCP (and therefore inherited to all projects). 

**My hypothesis:** As per [here](https://cloud.google.com/billing/docs/how-to/billing-access), although we have GCP JIT configured and working to request roles from ALL projects within GCP, due to the nature of the IAM Resource Hierarchy and the fact that **billing** as an entity sits outside of org-level and project-level, then JIT is failing the ability to assign this role since it does not "technically" exist at either level of IAM. (?)

**Hoping to confirm:**

1. If my hypothesis is correct
2. Is anyone else seeing the same problems?
3. If so, how did they identify a workaround within JIT if possible?

TYIA!

**Comment by jpassing** [comment]
Yes, billing accounts are a bit special in that they're an organization-level resource, not a project-level resource. JIT Access operates on the project-level (i.e., it grants temporary access to individual projects), which means you currently can't use it to manage temporary access to billing accounts.

However, the error message you quoted doesn't actually come from JIT Access, but the IAM API. 

Some roles can only be granted on certain resources. For example, you can grant `roles/billing.viewer` on a billing account or an organization, but you can't grant it on a project. I guess your Terraform code violated one of these rules by trying to grant a role on an incompatible resource?
